pycontw/pycon.tw

src/pycontw2016/settings/base.py
src/pycontw2016/settings/local.py
src/pycontw2016/settings/production.py
src/pycontw2016/urls.py

Site-wide path prefix (i.e. WSGI mount point) will now be
controlled in the WSGI server via the SCRIPT_NAME variable.
The project will not take it into account.

Remove URL_PREFIX and cleanup settings

---

src/static/css/main.scss
src/static/css/themes/_proposals.scss
src/templates/dashboard_base.html
src/templates/users/user_dashboard.html
src/templates/users/user_profile_update.html
src/users/forms.py
src/users/tests/test_views_dashboard.py
src/users/tests/test_views_signup.py
src/users/views.py

修正了 #39 裡提到的一些東西。
最主要的部分：如果訪問 `user_dashboard` 的使用者尚未認證或 profile 不完整，我現在直接把他 redirect 到 `user_profile_update`。這樣註冊流程會順很多，也不用煩惱非 valid speaker 在 proposal 列表會空一塊的問題（因為看不到）。
其他修改：
1. Self-Introduction → Biography
2. Biography 欄位改成 `textarea`，裡面用 monospace font。
3. 其他很多用詞

修正 dashboard 細節

---

src/templates/contents/en/speaking/cfp.html
src/templates/contents/zh/speaking/cfp.html
src/templates/index.html

(Issue #5)
在 `index.html`, `cfp.html` 加入 og 資訊
將 `cfp.html` 中的 “PyCon 2016 Taiwan” 改為 “PyCon Taiwan 2016”

在 index.html, cfp.html 加入 og 資訊

---

src/core/views.py
src/pycontw2016/urls.py
src/static/data/500.html
src/templates/500.html

Fix #23.
我盡可能把所有的 assets 都 inline 了，避免可能的錯誤。翻譯等進 master 後在 Transifex 上進行。
Django 另外也提供 400 和 403 的錯誤頁面，不過應該比較沒有需要？
為方便起見，如果想直接看這兩個頁面，可以直接訪問 `/404/` 和 `/500/`（學 GitHub 的做法）。
我另外在 `static/data/500.html` 做了一個完全 static（可以直接顯示，不需經過 Django，也沒有 i18n）的錯誤頁面，以防止前面的錯誤頁面又出錯。麻煩之後 deploy 時直接[在 nginx 設定](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page) `error_page 500`。

Implement error pages

---

src/proposals/management/commands/export_proposals.py

Export both talk and tutorial proposal info as JSON.
Usage:
python manage.py export_proposals > proposals.json

Add new management command export_proposals

---

src/static/css/_bootstrap-variables.scss
src/templates/base.html

This supersedes #111 and fixes #98.
Safari on OS X:
Edge on Windows 10:
Internet Explorer on Windows 10:

Apply Noto Sans TC (via Google webfont)

---

src/core/widgets.py
src/static/js/tools/simplemde-setup.js

原本的實作使用 `mark_safe`，這代表如果 Markdown 欄位中有 raw HTML 會直接被執行，產生 XSS 風險。
新的實作改傳 escaped data，然後在 render 的時候用 `DOMParser` 把輸入值 unescape，然後再傳入 marked.js render 成 HTML，順便讓它負責剩下的 sanitation。
[`DOMParser` 只在 IE 10 以上支援](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#Browser_compatibility)，所以在較舊的瀏覽器上我就不 render 了，直接顯示 raw Markdown，應該也還可以接受。
處理 HTML unescaping 的參考資料：  
http://stackoverflow.com/questions/1912501#34064434

修正 Markdown 欄位的 XSS 風險

---

src/core/utils.py
src/reviews/views.py

見 #155。我加了一個 `SequenceQuerySet` 讓 shuffle 後的結果可以直接被 template 使用，不需要特別分辨是 queryset 還是 list。

手動洗牌 review 的 proposal list

---

src/core/utils.py
src/templates/reviews/talk_proposal_list.html

Add missing magic methods for API compatibility.
We should use .count anyway.

Fix length bug on querysets

---

src/templates/reviews/review_form.html

想不到 `objective` 有，這個欄位卻沒有的理由⋯應該是漏掉了？

Add |linebreaks to abstract field

---

src/reviews/views.py
src/templates/reviews/_includes/proposal_table.html
src/templates/reviews/_includes/review_table.html

The list view now carries the query string when going to the review
form view. The latter can then uses it when redirecting back to the
list view.
Fix #158.

Carry query string from list view to form

---

src/proposals/models.py
src/reviews/views.py

原本有個小問題是 `ReviewForm` 可以 review 已取消的 proposal（雖然因為沒有連結，大概也很難找到 proposal 網址來 review）。

Refactor cancel filter into filter_reviewable

---

src/static/css/components/_tables.scss
src/templates/contents/en/registration/ticket-info.html
src/templates/contents/zh/registration/ticket-info.html

內容以中文版為主，所以中文的文案只有小修一點，主要是飲食需求那段。
結構上的修改：
1. 我把一般票統一放到最上面了，總之以中文版為主。
2. Table 的標題列放到 `thead`，CSS 也相應修改。
我把日期格式也統一了。

Cleanup and reword ticket info pages

---

src/static/css/pages/_front.scss

<table>
<thead>
<tr><th>Before</th><th>After</th>
</thead>
<tbody>
<tr><td><img src="https://cloud.githubusercontent.com/assets/605277/14845904/a200ee1e-0c93-11e6-8741-11d6df4a3cb1.png"></td><td><img src="https://cloud.githubusercontent.com/assets/605277/14845911/ac94ad5c-0c93-11e6-9b91-4fab3bbd6ec9.png"></td></tr>
</tbody>
</table>

Add a little margin between speaker photo and bio

---

src/users/forms.py
src/users/tests/test_forms.py
src/users/views.py

原本的 `UserCreationForm` 無法用在 admin，所以把一些功能拆到 `PublicUserCreationForm`（公開介面改用這個），讓 admin 可以使用前者。

在 admin 與公開介面使用不同的 user creation form

---

src/templates/events/talk_list.html

Quick hack. So the team can have more time refine the work.
Google doc looks like the following,
I didn't use orange because it is a bit harder to read, probably due to the font.

Add gdoc preview version of the program schedule

---

src/events/migrations/0002_sponsoredevent_slug.py

產生 slug 時使用欄位長度設定 slice 輸出，避免 DataError

根據欄位設定限制 Slug 輸出長度

---

requirements/base.txt
requirements/dev.txt
src/core/middlewares.py
src/pycontw2016/settings/base.py
src/pycontw2016/settings/local.py

Upgrade Django version to 1.10.4. Some packages are also upgraded to
support newer version of Django.
`LocaleFallbackMiddleware` is also modified to new style middleware
introduced in Django 1.10.

Upgrade to Django 1.10.4.

---

src/pycontw2016/settings/local.py
src/pycontw2016/urls.py

Add `INTERNAL_IPS` settings and URLconf for Django Debug Toolbar.
I forgot to include these settings in PR #282.

Add Django Debug Toolbar configurations.

---

src/static/js/tools/simplemde-setup.js

原本的版本沒辦法處理 inline HTML (全部 tag 會被移除)，現在這個版本可以。順便用 `Array.prototype.forEach` 讓程式漂亮一點。
剛剛在看投影片發現的。應該是沒有實際的顯示問題。

改寫 Markdown → HTML 函式

---

src/templates/pycontw-2017/contents/en/speaking/cfp.html
src/templates/pycontw-2017/contents/en/speaking/talk.html
src/templates/pycontw-2017/contents/zh/speaking/cfp.html
src/templates/pycontw-2017/contents/zh/speaking/recording.html
src/templates/pycontw-2017/contents/zh/speaking/talk.html
src/templates/pycontw-2017/contents/zh/speaking/tutorial.html

主要集中在兩部分
cfp 
- 加上粗體字的html, 但style sheet還沒上
- 增加Everyone pays policy連結
- Tutorial部分還是T.B.D(暫時先放舊的過去）
talk
- 加上PyCon TW 2016連結
其他順帶發現的issues會再ref過來

update contents of speaking

---

src/proposals/models.py

剛剛發現 `proposal/modal.py` 內的 30min 演講長度沒改到。

modify talk short duration to 30min

---

src/static/css/pages/_proposals.scss
src/templates/default/reviews/_includes/previous_review_table.html

如果 reviewer 有留言，只是被隱藏，顯示一個提示訊息（而不是空白）。這樣投稿人看起來會比較合理（會知道是留言被隱藏，而不是 reviewer 評分卻不寫為什麼）。

Show hint if there is a redacted review comment

---

README.md

We have used this repository for 2017 and 2018 as well. The code base has changed a lot when time goes by. I suggest to change the name to be more generic. Even more, we may consider to change the repository name as well.

Use a more generic name

---

Dockerfile
requirements/base.txt
requirements/production.txt
src/pycontw2016/settings/production.py

This pull request adds Dockerfile that can be used to generate container image for the deployment of the 2016 website.
uWSGI is used instead of Gunicorn because uWSGI can serve static and media files without external dependencies, which provides better encapsulation IMHO; since Gunicorn will require **additional service/program that known where static and media files are located**.
Additionally, various modifications are made (specifically pinning libsass version, update `pycontw2016/settings/production.py`) in order for the application to start normally (there might be better way to get around these, I'm open to comments).

Add Dockerfile for the 2016 Website

---

requirements/base.txt

This pull request fixes typo pointed out in https://github.com/pycontw/pycon.tw/pull/505#discussion_r265896869

Fix typo in requirements/base.txt on the 2016 branch

---

Dockerfile
requirements/base.txt
requirements/production.txt

This pull request adds Dockerfile that can be used to generate container image for the deployment of the 2017 website, similar to [the pull request for the 2016 website #505](https://github.com/pycontw/pycon.tw/pull/505).
A few differences from the Dockerfile for the 2016 website:
* Use Python 3.6
* Ignore 'dbfpy/dbfnew\.py' in the `compileall` step since that file is written in Python 2 syntax, and cause `compileall` to fail

Add Dockerfile for the 2017 Website

---

DEPLOY.md
Dockerfile
requirements/production.txt

The pull request adds `Dockerfile` for creating container image (similar to [the pull request for 2017 website #532](https://github.com/pycontw/pycon.tw/pull/532)) as well as instruction on how to deploy the website to production in `DEPLOY.md`.
`django-picklefield` is pinned to version 1.0.0 since later version no longer supports Django 1.10, which is used for the 2018 website.

Add Dockerfile and Deployment instructions for the 2018 Website

---

DEPLOY.md
Dockerfile
requirements/production.txt

The pull request adds `Dockerfile` for creating container image (similar to [the pull request for 2018 website #542](https://github.com/pycontw/pycon.tw/pull/542)) as well as instruction on how to deploy the website to production in `DEPLOY.md`.
Again, `django-picklefield` is pinned to version 1.0.0 since later version no longer supports Django 1.10, which is used for the 2018 website.

Add Dockerfile and Deployment instructions

---

src/static/pycontw-2019/styles/_button.scss
src/static/pycontw-2019/styles/_index-partners.scss

Style update in #546 changes how the button styling on index page, this PR fixes the sponsorship button display

Update index page button style

---

src/templates/pycontw-2019/contents/zh/events/open-spaces.html

There is an extra line of this page https://tw.pycon.org/2019/zh-hant/events/open-spaces/

Fix redundant typo of open space introduction

---

src/templates/pycontw-2019/_includes/staff.html
src/templates/pycontw-2019/ccip/sponsors.html
src/templates/pycontw-2019/ccip/staff.html

新增ccip 的sponsor和staff page
staff page:
新增機動跟OPass開發兩組，機動我翻成Maneuvering不知道是不是最適合
另外這兩個翻譯可能要請人去補一下
審稿委員還在等

feat: 🎸 add ccip staff and sponsor page

---

src/templates/pycontw-2019/_includes/footer.html

fix: 🐛 add staff href back in footer html

---

DEPLOY.md
Dockerfile

The current deb buster repository provides 10.x nodejs[1] and will override the expected nodejs version (8.x) to make the deployment fail. This pull request fixes the expected nodejs and tested with a clone pycontw 2019 website served with a postgresql and nginx service. 
[1]
```
nodejs:
Installed: (none)
Candidate: 10.15.2~dfsg-2
Version table:
10.15.2~dfsg-2 500
500 http://deb.debian.org/debian buster/main amd64 Packages
8.16.0-1nodesource1 500
500 http://deb.nodesource.com/node_8.x stretch/main amd64 Packages
```

Update Dockerfile to fetch expected nodejs version

---

src/templates/pycontw-2020/contents/en/about/code-of-conduct.html
src/templates/pycontw-2020/contents/en/event/open-spaces.html
src/templates/pycontw-2020/contents/en/speaking/cfp.html
src/templates/pycontw-2020/contents/en/speaking/recording.html
src/templates/pycontw-2020/contents/en/speaking/talk.html
src/templates/pycontw-2020/contents/en/speaking/tutorial.html

Add following en content :
- about: coc 
- event: open-spaces
- speaking: cfp, recording, talk, tutorial

feat: add 2020 cfp, about, event content (en)

---

src/templates/default/reviews/review_form.html
src/templates/default/reviews/talk_proposal_list.html

staticfiles template tag library is deprecated in Django 2.1. Change it to `{% load static %}`.
Quick Reference: https://stackoverflow.com/questions/55929472/

Fix compatibility issue for Django 3.0

---

src/static/pycontw-2020/styles/page.scss
src/templates/pycontw-2020/contents/en/about/pycontw.html
src/templates/pycontw-2020/contents/en/speaking/cfp.html
src/templates/pycontw-2020/contents/zh/about/pycontw.html
src/templates/pycontw-2020/contents/zh/speaking/cfp.html

We have some background decorating images that overflows outside the page. On mobile devices, it will cause scrolling and we do not want that. This fixes the bug.

Fix scrolling on mobile devices bug

---

src/static/pycontw-2020/styles/_layout.scss
src/static/pycontw-2020/styles/_pycontw-year-ribbon.scss
src/static/pycontw-2020/styles/index.scss
src/static/pycontw-2020/styles/page.scss
src/static/pycontw-2020/styles/pages/_about.scss

This fixes the bug when the content is not long enough and the footer isn't at the bottom, like the following screenshot:

Fix sticky footer bug in zh speaking/recording page

---

src/static/pycontw-2020/styles/_layout.scss
src/templates/pycontw-2020/contents/en/sponsor/prospectus.html
src/templates/pycontw-2020/contents/zh/sponsor/prospectus.html

The table is larger than the page. But it won't scroll on x-axis. This PR fixes this problem by make it scrollable on the prospectus page.

Fix prospectus scrolling

---

src/templates/pycontw-2020/contents/en/sponsor/sponsor.html
src/templates/pycontw-2020/contents/zh/sponsor/sponsor.html

The link points to 2019 gdoc. We will let the sponsorship team decide if we want to put the gdoc link back later.

sponsor: prospectus: rm gdoc registration link

---

README.md

I think the `makemessages` command changed over versions. We need to specify `--locale _src` to make messages to the _src locale.

Update makemessage instruction

---

src/core/templatetags/pycontw_tools.py

As mentioned in the [comment](https://github.com/pycontw/pycon.tw/pull/696#issuecomment-602017232) of #696, the url pattern in the development environment is `/<LANGUAGE>/<CATEGORY>/.../...` but it's `/<LANGUAGE>/<CATEGORY>/.../...` in the production/staging environment, which is not supported by the customized template filter `get_path_category()`.
Change the regex matching function in `get_path_category()` from `re.match()` to `re.search()` to support two aforementioned url formats.

Fix get_path_category() for production url pattern search

---

src/static/pycontw-2020/styles/page.scss

I have no idea why I made the navbar as flex at the first place.
Maybe I was just trying to make "My PyCon" rightmost, and try to
do that by making the nav items and "My PyCon" as flex items.
But in the end, "My PyCon" remains as an item inside the nav,
which makes it only one element inside the flex, and this cause
a problem in Safari, making the entire flex container with no
height, so the display is wrong and you cannot hit any item on the
menu.

Fix navbar display issue in safari

---

.gitignore
Dockerfile
docker-compose.yml

We did not automate the flow so we needed to compile .po files locally
first and then commit the corresponding .mo files into the repository.
Automate the generation of .mo files will free us from committing .mo
binaries into a repository.
verification steps, on the staging site:
1. `find ./ -name "*.mo" -exec rm {} \;` to remove all existing .mo files
1. `docker-compose up --build -d`
1. `docker exec -it <container ID> bash` and check the timestamp of the generated .mo files `find ./ --name "*.mo" -exec ls -alh {} \;`
1. also, check the staging site pages to make sure the translation is working.

Generate .mo files automatically per deployment

---

src/proposals/management/commands/export_proposals_create_time.py

Requirement of the agenda group, hope the proposal's create time info can be filtered by whether 'cancelled'.
You can run
`python manage.py export_proposals_create_time`
to see new result.

Modify command: export_proposals_create_time

---

src/reviews/views.py

When we are in review stage 2, it will try to retrieve the previous
review data and fill in to the fields as default values.
First, it tries to fetch if there are reviews in the same stage. If not,
it will try to fetch if there are reviews in the previous stage.
The first one does not work because it looked at the wrong parameter.
It should be looking for 'instance' instead of 'object' in the form
kwargs of the Django generic ModelFormMixin. Fixing this fixed the issue
and it will display the correct default value.
A keyword change from 'object' to 'instance' in the form kwargs lookup.
1. Go to Django Admin and modify the django registry with the corresponding values:
``` …
```

Fix wrong default review form values

---

src/pycontw2016/settings/base.py

Revert the changes made to src/pycontw2016/settings/base.py in #783 (specifically a03d7880).
For development environment the ALLOWED_HOSTS setting canbe left as an empty list, since [Django documentation stated](https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts) that
> When DEBUG is True and ALLOWED_HOSTS is empty, the host is validated against ['localhost', '127.0.0.1', '[::1]'].
See #792 for more detail.
```cmd
cat src/pycontw2016/settings/base.py | grep ALLOWED_HOSTS
```
In ALLOWED_HOSTS setting in src/pycontw2016/settings/base.py is set to an empty list, which was what it was set to previously
#792

Use an empty ALLOWED_HOSTS setting

---

src/core/utils.py

I tried to update pages found at `/events/*`, but keep on getting 404 Not Found error even in development mode without any more information provided. After tracing through the code I realized it is because many of those views use the TemplateExistanceStatusResponse response class, which hides the TemplateDoesNotExist exception. (I guess because it introduce too much logging noise on production?)
This is of course due to unfamiliarity with Django and the code-base itself on my part, but I think it maybe more helpful to reraise TemplateDoesNotExist or UnicodeEncodeError exception instead of hiding it behind a 404 Not Found when we're in development mode; so it's easier to diagnose the issue.
1. Start the …

Reraise template-resolution exceptions in development mode

---

README.md
requirements/base.txt

移除readme.md對於tx的描述(該套件已棄用)，將主要的翻譯方式改為輸入```python manage.py compilemessages```指令
```
python manage.py compilemessages
```
將```/src/locale/{各國語系}/LC_MESSAGES/django.po```編譯成同路徑的```django.mo```(django i18n執行會讀的檔案)
https://github.com/pycontw/pycon.tw/issues/761

update description of translation in readme.md

---

src/templates/pycontw-2020/contents/en/events/passion-fruit.html
src/templates/pycontw-2020/contents/zh/events/passion-fruit.html

In the changes in PR #785, the path of event info image is `pycontw-2020/assets/warm-session/passion-fruit/Info.png` but  `pycontw-2020/assets/warm-session/passion-fruit/info.png` is given on both en & zh pages. It can be displayed successfully in the environment with case-insensitive settings but failed in our production environment.
1. Go to `<host>/2020/<lang>/events/passion-fruit/`.
2. The event info image should be displayed successfully.
The image is shown.
See #767 for the requirements.
This is what we saw on staging:

Correct the path of info image on passion-fruit page

---

src/templates/pycontw-2020/contents/en/registration/financial-aid.html
src/templates/pycontw-2020/contents/zh/registration/financial-aid.html

This PR is sent for fulfilling the request in #815, including 
- more eye-catchy text with a link to form 
- make it bold.
- add a Font Awesome icon ([fa-external-link](https://fontawesome.com/v4.7.0/icon/external-link)) following the text (see the pictures below).
- updating the form link
- I believe the link given in #815 is the same as the current one (@yychen please help confirmed this), so it's not updated. 
1. Go to FA page `<host>/<lang>/registration/financial-aid/`
Should see the link to the application form is more eye-appealing.
see #815
- original 
- modified in this PR
In this PR, the link to Font Awesome CSS file from CDN is used for easier implementation since we want this to be online tomorrow. However, it definitely increases the loading …

chore(style): make link to FA application form more obvious 

---

contrib/docker-entrypoint.sh

Compile localized translation when starting development environment
1. Start the development environment with the `enter_dev_env.sh` script
2. Open `localhost:8000/zh-hant/` with web browser
Content of the webpage is displayed in Traditional Chinese.
See #761 for more context.

Compile localized translation when starting development environment

---

src/templates/pycontw-2020/contents/en/about/community.html
src/templates/pycontw-2020/contents/zh/about/community.html

Modify Taichung.py's community link to facebook group.
(Tho old one has been closed)
Taichung.py 的meetup社群已移除，因此將原連結改為[Taichung.py的facebook社團](https://www.facebook.com/groups/780250978715991/)連結
```python manage.py runserver```
點選[在地Python社群](https://tw.pycon.org/2020/zh-hant/about/community/)中的Taichung.py
會連結至[Taichung.py的facebook社團](https://www.facebook.com/groups/780250978715991/)
#825

modify_TaichungPy_community_link

---

src/reviews/admin.py

Add search bar(search on proposal title) in review admin. 
1. Go to `admin/reviews/review/`
2. Search review by proposal title
Should see review with proposal title we searched
#804 

Add search bar(search on proposal title) in review admin.

---

src/templates/pycontw-2020/index.html

The CfP has ended and the selected talks are announced. Let's update the portal of the landing page with the talk list instead of CfP.
1. Go to the index page
2. Click "Talks" button
You will be redirected to the "talk list" page.
**Screenshots** of the changed page

List talks instead of CfP in the landing page

---

src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/pycontw-2020/styles/_palette.scss
src/static/pycontw-2020/styles/_tabbing.scss
src/static/pycontw-2020/styles/pages/_keynotes.scss
src/templates/pycontw-2020/_includes/menu.html
src/templates/pycontw-2020/contents/_default/events/keynotes.html

Adjusting keynotes page to 2020 style
1. Go to the `/events/keynotes/` URL
You should see the keynotes page with style aligning with those mentioned is #838.
#838 
None

feat(keynotes): adjust to 2020 style

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/pycontw-2020/styles/_box.scss
src/templates/pycontw-2020/_includes/menu.html
src/templates/pycontw-2020/events/tutorial_list.html

add pycontw 2020 style scss for tutorials
✅ Closes: close #839
- [*] **New feature**
change _box.scss style for pycontw 2020 style
1. Go to '/events/tutorials/'
2. See result
Right color for pycontw2020
#839

feat: 🎸 add pycontw 2020 style

---

src/templates/pycontw-2020/_includes/menu.html

Add a link to `/events/sprints` in the menu
1. Hover over the events menu in the front page
Link to the Sprints page is within the events menu
Implemented as per @yychen's [comment](https://github.com/pycontw/pycon.tw/pull/863#pullrequestreview-463708865) 

feat(sprints): add menu link

---

src/templates/pycontw-2020/events/sponsored_event_detail.html
src/templates/pycontw-2020/events/talk_list.html

sponsored talks go back in talk list!
✅ Closes: #865
- [ * ] **Bugfix**
let show sponsored lists in  talk list
The sponsored lists don't show in  talk list
We can see the sponsored list in talk list
#865

feat: 🎸 already implement this issue request

---

src/ext2020/views.py

The main conference rooms are R1, R2, R3 instead of R0, R1, R2.
1. Go to localhost:8000/admin/ext2020/attendee/ and add an attendee with 32-char token and verified set to true
2. Go to localhost:8000/ext/live?token={TOKEN} (where {TOKEN} is the token you just generated)
3. You should see the rooms are 1, 2, 3, instead of 0, 1, 2.
If you want to test the youtube, you can go to Django Registry ( localhost:8000/admin/registry/entry ) and add a record, where key is `pycontw-2020.live.r1` and the value is the youtube id.

Change the live room name

---

src/ext2020/urls.py

Make both `ext/discord` and `ext/discord/` work (also applies to `ext/live`)
1. Go to localhost:8000/ext/discord/
2. See 404
It should show the discord page.

Fix ext2020 trailing slash problem

---

src/templates/pycontw-2020/events/_includes/schedule_keynote_event.html

We've changed the keynote path from events to conference. The schedule renderer path needs an update.
1. Go to localhost:8000/conference/schedule/new
2. Check on any keynote event link
3. It leads to the wrong URL
It should be the correct URL, which is '/conference/keynotes'
#909 
It's weird that if you click on, say "wenyu-su"'s keynote link, it doesn't jump to the specific section. Need to check this as well.
After the fix is applied, re-generate schedule is required.
Go to '/2020/conference/schedule/new' and generate a new one on the production site.

Fix keynote wrong link in the main schedule

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/templates/pycontw-2020/_includes/ext/discord.html

The invitation link needs to be updated. 
1. Go to `<host>/<lang>/ext/discord/`
2. Click on the invite link
3. See the current one is expired
The invite link should work
No issue is related. This request is from the program team.

chore(discord): update invite link

---

src/ext2020/models.py
src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/pycontw-2020/styles/pages/_community-track.scss
src/templates/pycontw-2020/events/_includes/community-track-overview.html
src/templates/pycontw-2020/events/community_track.html

update show soft limt change font color.
#879

update show soft limit

---

src/templates/pycontw-2020/events/_includes/schedule_keynote_event.html

The links to keynote on the schedule page are correct but do not lead to the correct session. Take Marriata's session as an example, the link is `https://tw.pycon.org/2020/zh-hant/conference/keynotes/#mariatta-wijaya` but it does not jump to the correct session. The root cause is the id of the keynote session is now `keynote-speaker-{{slug}}` (see [here](https://github.com/pycontw/pycon.tw/blob/master/src/templates/pycontw-2020/contents/_default/conference/keynotes.html#L33)).
1. Go to the schedule page and click on the keynote event 
It should lead the user to the target session on the keynote page 
#910

fix(schedule): keynote id in the link is incorrect

---

src/templates/pycontw-2020/events/_includes/community-track-overview.html
src/templates/pycontw-2020/events/_includes/community-track.html

In #905, the choice count of each venue is shown in the overview section:
However, it's not displayed in the topic & venue section:
1. Go to `<host>/<lang>/conference/community-track/`
Should see the choice count in both the overview section & the topic section.
#879 #905

fix(community-track): also display choice count in topic session

---

src/static/pycontw-2020/styles/pages/_job-listings.scss

the original image size is wrong on mobile

fix cover image size

---

src/static/pycontw-2020/styles/pages/_events.scss

- Fix the styling issues mentioned in #907 and #922
1. Go to `/events/schedule`
1. Scroll to an event that has long title
1. Toggle the browser viewport and see if the texts are not cropped off
1. Go to `/events/schedule`
1. Adjust the browser to a mobile viewport breakpoint
1. Click on the menu icon and see if the display mentioned in the issue has gone
- In mobile view, at `/events/schedule` route, the menu shouldn't contain the schedule time headers
- There shouldn't be cropped texts in event titles among different viewports
- #907
- #922

fix(schedule): Fix styles

---

src/events/views.py

Unhandled error when trying to access tutorial details.
Part of the debug info:
1. Go to `<host>/<lang>/conference/tutorials/`
2. Click on any button below the description of each tutorial
Should display the page successfully
#928 
Currently not fully understand all code for the tutorial detail page. Just do the hack for preventing the 500s and will try to do it in a better way later

fix(tutorial-detail): hack for stopping 500s

---

src/events/views.py
src/templates/pycontw-2020/events/talk_detail.html

[This talk](https://tw.pycon.org/2020/zh-hant/conference/talk/sponsored/practical-enterprise-jupyterhub-deployment-and-mlo/) is the only sponsored event and also one of the talks in the community track. However, the location on the detail page cannot be derived successfully and is shown as `Other`.
The solution is simply to insert the sponsored event into context data (similar to what've done in `ProposedEventMixin`).
1. Go to `<host>/<lang>/conference/talk/sponsored/practical-enterprise-jupyterhub-deployment-and-mlo/`
The correct location should be shown as below:
N/A

fix(sponsoredEvent): fix cannot display location issue

---

src/templates/pycontw-2020/base.html

Load the missing weights of the font "Quicksand".
1. Go to localhost:8000/conference/schedule on a Windows box
2. The fonts look weird
It should look nice.
#907 
Original:
After loading the weights:

Load 600 and 700 font

---

src/templates/pycontw-2020/contents/en/covid-19/guidelines.html
src/templates/pycontw-2020/contents/zh/covid-19/guidelines.html

Add the health declaration link on the COVID-19 guidelines page. It could possibly accelerate the registration process.
1. Go to `<host>/<lang>/covid-19/guidelines/`
The viewers should be able to link the form
N/A

chore(covid-19-policy): add health declaration form link

---

src/templates/pycontw-2020/ccip/community_track.html
src/templates/pycontw-2020/events/_includes/community-track-traffic.html
src/templates/pycontw-2020/events/community_track.html

Move the traffic block into a snippet html template so that the original and ccip version of community track page can include it.
1. Go to localhost:8000/cip/community-track
2. Scroll down to the last part
4. The content is inconsistent to the original community track page. Traffic info is not displayed in the OPass version.
The OPass version and the web version should be the same. Traffic info should be on both sides.

Add traffic info into OPass community track page

---

src/events/admin.py

- Add slido_link field to admin in SponsorEvent
1. Go to 'admin/events/sponsoredevent' page. 
2. Click on any event
3. Check the field is showed
The slido link field will appeared as following screenshot.
to [how to wirte the perfect pull …

feat(event): Add slido_link field to admin in SponsorEvent

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/templates/pycontw-2020/events/_includes/community-track-overview.html
src/templates/pycontw-2020/events/_includes/community-track.html

Block community track if it is already full. User cannot select it anymore.
1. Go to localhost:8000/conference/community-track
2. The community track with selected attendees more than it's capacity is still available
It should block user from selecting already full track

Block full track

---

src/static/pycontw-2020/styles/_index-partners.scss
src/static/pycontw-2020/styles/index.scss
src/static/pycontw-2020/styles/page.scss
src/templates/pycontw-2020/index.html

- Fix wrong window width in mobile device
- Uncomment volunteer and sponsor section
1. Go to 'Index Page'
2. Check if the "Become a volunteer" and "Sponsor PyCon TW" buttons exist
---
1. Go to https://tw.pycon.org/2020/zh-hant/conference/talk/1164337168361980290/ 
2. Open the debugger and switch to mobile mode, or view the page from your phone.
3. Check if the layout is displayed normally.
A clear and concise …

fix(talk_detail): Fix wrong width in talk detail view

---

src/static/pycontw-2020/assets/keynotes/mariatta-wijaya.json
src/templates/pycontw-2020/contents/_default/conference/keynotes.html

put keynote slides url to file

Put keynote slides

---

src/pycontw2016/settings/production/pycontw2021.py

Fix  https://github.com/pycontw/pycon.tw/pull/976, import gettext_lazy in production/pycontw2021.py
( Because  https://github.com/pycontw/pycon.tw/pull/976 has be merged, thanks for @mattwang44  reminder )
Import gettext_lazy in production/pycontw2021.py.
No error occurs when the 2021 production setting is executed.
https://github.com/pycontw/pycon.tw/pull/976

Import gettext_lazy in production/pycontw2021.py

---

.gitignore
src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/users/forms.py

- Add photo size validation in profile update form
1. Go to user profile page
2. Upload 8 x 8 image that is larger than 10M.
https://trello.com/c/j0ezAODh/24-fix-all-the-bugs-found-during-the-proposal-system-testing

feat(user_profile_form): Add photo size validation

---

src/core/tests/test_middlewares.py
src/core/tests/test_views.py
src/core/views.py
src/events/tests/renderers/test_render_event.py
src/pycontw2016/urls.py

We're now attempted to migrate all the attendee-facing pages to our new frontend project and remain the pages related to the proposal & review system in pycon.tw backend project. Thus, remove the URLs that are deprecated.

feat(url): remove old URLS

---

src/users/views.py

**[WHY]**
The redirection target stored in the query params (?next=/path/to/submission/page) can be removed after the user changes language, which causes an unhandled exception.
**[HOW]**
Redirect to user dashboard instead if the aforementioned situation happened.

fix(coc): handle redirection target after posting the coc agreement

---

src/events/api/serializers.py
src/reviews/views.py
src/templates/default/reviews/_includes/proposal_table.html

Return 5XX when accessing the review portal with ordering by review count (`<host>/<lang>/reviews/?order=count`) as a reviewer. The error log is shown below:
Using default alias solves this issue.

fix(reviews/views): use default alias for annotation

---

src/sponsors/api/views.py

In the response of `GET` `/api/sponsors/jobs/`, the job list is mistakenly copied to all the sponsors.
1. Call API: `GET` `/api/sponsors/jobs/`
2. Checkout response
The job lists are correctly grouped by the sponsors.

fix(api/openrole): duplicated job lists

---

src/events/api/serializers.py
src/events/api/urls.py
src/events/api/views.py
src/users/models.py

The event API response format is defined based on the 2020 website since the frontend design of the 2021 website was WIP at the time, which does not perfectly meet the new spec.
1. Set the value of speaker profile URL to be an empty string if ID (including GitHub ID or Twitter ID) is not given.
2. Return the full URL of the speaker thumbnail (e.g. `<host>/media/XXX.jpg`) rather than just the path (e.g. `/media/XXX.jpg`).
3. Add/remove the fields to/from the response to meet the design spec.
4. Make Talk List/Detail APIs also retrieve the data of the sponsored events.
- Current
```
[{
"id": Number,
"title": String,
"category": String,
"labels": String, // unused, always empty
"speakers": [
{
"name": String,
"facebook_profile_url": URL,
"github_profile_url": URL,
"twitter_profile_url": URL, …
```

Modify event API response format for frontend design spec

---

src/sponsors/api/views.py

The sponsor name in open role API response is used by frontend and then passed to GA for counting the click on sponsor logo. The field is retrieved from db by the field `name` from `sponsor` model, but `name_en_us` is used in sponsor API, which cause the discrepancy between those two API and make it harder to joining those two metrics.
Update the open role API to unify the value of sponsor name to solve this issue.

chore: use sponsor name in en-us for open role api

---

src/events/api/views.py

Let schedule API to return the keynote speaker's name and keynote title with i18n.
1. Go to http://localhost:8000/api/events/schedule/
Will see the keynote speaker's name, and the title is a dict with two keys: zh_hant, en_us.

fix(events/api/views.py): Let schedule API can return i18n str for keynote data

---

src/static/css/pages/_reviews.scss

As mentioned in this issue #1069, can't see counts on the panel, because of the font color.
I give it with color `#000` for now.
1. Make some fake data on proposals and do the review.
2. Go to `http://0.0.0.0:8000/zh-hant/reviews/`.
The numbers should appear in the panel.
#1069

fix: add font color to show the count on the review voting panel

---

src/reviews/views.py

In summary, the review page adopts pagination on the proposal listing (100 per page) in the views but the frontend page does not handle the pagination, which leads to displaying the wrong total number as 100. The reason why this issue is firstly-discovered today since released (6 years ago) is it's the first time we received more than 100 proposals.
Simply raise the `paginate_by` of Django's `ListView` as a temporary solution.
#1072

fix(reviews/talk_proposal): enlarge paginate_by as temp solution

---

src/static/css/vendors/bootstrap/_navs.scss

The color of the navbar on the proposal page is not clear:
change color as follow:

fix(proposal): navbar color

---

src/conftest.py
src/events/api/urls.py
src/events/api/views.py
src/events/tests/api/test_list_speeches.py

- Add `api/events/speeches/category/<str:category>` endpoint and its related view and test
1. Running GET `{API_HOST}/api/events/speeches/category/WEB` or others category like DATA, ML, etc.
List all events which have the corresponding category and have the same schema as the original Speech List API.
#1080

feat(events/api): add GET SpeechListByCategory views, urls and tests

---

src/reviews/views.py

- The original counting for review is wrong is because the previous code didn't sum up the stage 1 and stage 2.
- Make some reviews in both stage 1 and stage 2, and try to review them in different stages.
- The total of 個人審查數據 should be the same as 已審查的演講提案
#1086

fix: fix the statistic of the review counting

---

src/events/api/serializers.py

…and tutorialList's api
Add location and begin_time into events/talk, tutorial's api
Please visit `/api/events/speeches` 
See if data with event_type talk or tutorial have location and begin_time

Add location and begin_time to talk and tutorial list's api

---

src/pycontw2016/settings/production/base.py

1. put your `google-cloud-storage.json` under src/
2. (Workaround) Rewrite https://github.com/pycontw/pycon.tw/blob/master/src/sponsors/models.py#L14 to `return default_storage if False else GoogleCloudStorage()`
3. Copy L138 to L142 in https://github.com/pycontw/pycon.tw/pull/1108/files#diff-2ceb691b10b9d00dad55f62e98e5bf2916af93f9138538355a20604d2650ea8dR138-R142 to `pycontw2016.base.py`
4. Run `docker-compose -f ./docker-compose-dev.yml up`
self-describe enough about how you change the …

feat(settings.production.base): set GS_DEFAULT_ACL to publicRead

---

src/proposals/api/urls.py
src/proposals/api/views.py
src/proposals/tests/api/test_proposals_summary.py
src/proposals/tests/conftest.py
src/pycontw2016/urls.py

- add proposals api url
- add proposals api view
1. Go to 'http://localhost:8000/api/proposals/'
response will be
1. num_proposed 
2. num_stage_1_reviews
3. num_stage_2_reviews
#1127

feat: add proposals api and view

---

src/static/css/pages/_proposals.scss
src/static/pycontw-2023/_includes/_bootstrap-variables.scss

Adjusted the text color of compare tab at reveiw edit view and the background color of the changed content for increase the color contrast.

Adjust color setting of review edit view

---

src/sponsors/translation.py

en-us name field of the sponsor model should be required as it's the field that allows us to differentiate sponsor info from the GA click count events. (see discord discussion thread [here](https://discord.com/channels/752904426057892052/1138015073126846504/1138035759379652669))
Saving sponsor data without an en-us name will be blocked with this PR.

feat(sponsor): make sponsor en name as a required field

---

src/ccip/views.py

* let session start/end time follow local timezone
1. Go to http://localhost:8000/ccip/
#1148 

feat(ccip): let session start/end time follow local timezone

---

Dockerfile
dev.Dockerfile

Use multi-stage feature on Docker to enable easy-read and better maintenance for Dockerfile
Two stages: node_stage and python_stage
node_stage: 
- handling node_modules and node **executable**, by using multi-stage with `FROM`, we can specify docker image taf and get the node run-time with no extra works (nvm and hardcoded download link)
- use buster-slim variant
python_stage:
- handling Python environment and web server instructions
- using slim-buster variant
- need to manually install libpq and GCC for pyscopg2 and uwsgi as we downsize from buster to slim-buster
Notes:
- need to align image variant to {size-variant}-{debian-variant} to make node executable executable (For example, both node_stage and python_stage needs to be **SLIM** **BUSTER**)
- Same
Size reduced up to 50% and more …

build(dockerfile): enhanced production dockerfile

---

src/ccip/tests/api/test_ccip.py

testing for attendee #1143 
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
to [how …

test(ccip): add test cases for ccip apis 

---

src/reviews/views.py
src/templates/default/reviews/_includes/proposal_table.html
src/templates/default/reviews/talk_proposal_list.html

Add category filed to proposal table. When you click on a category, the list of proposals will be filtered by the category you selected.
1. Go to review page
2. Click on category filed
Show the proposal list which was be filtered.
to [how to wirte the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-r …

[Feat] add category filter on review page

---

Dockerfile

fix node_modules path for production dockerfile
related to #1156 
After #1151 , the node_modules are misplaced. Should be in `usr/local/app`.
Re-build image using updated `Dockerfile`
No longer need a manual fix for node_modules path
#1156 
Run and tested in staging vm

fix `/usr/local/app/node_modules/.bin/node-sass: not found` 

---

src/static/css/pages/_proposals.scss

The background image is not shown when dev with the local server (but appears on staging/production).
1. run local server
2. bg image not shown and has error messages
no error msg and the background image has displayed

fix(static): proposal system bg img is not shown when local dev

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/sponsors/models.py

* **New feature**
需要增加一個贊助類別為「衝刺開發協辦單位」。
1. Go to the path admin site
2. add a sponsor to see if level 9 exists
3. Check output, should be as expected as in https://github.com/pycontw/pycontw-frontend/pull/553

feat(sponsors): add sprint-coorganizer level for sponsors api

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/css/components/support_box.scss
src/static/css/vendors/bootstrap/_navs.scss
src/templates/default/dashboard_base.html

- 修復中英文翻譯顯示錯誤的問題
- 讓顯示 AI summary 和 comment 的地方與 點選summary 和 comment 區塊保持間距
- 增加當內容過多時可 scroll 的樣式設定，避免內容 overflow 無法完整閱讀
1. 進入審查頁面
2. 點選其中一格稿件進入審查
3. 右下會看到 AI 給的建議小方框
4. 點擊小方框查看AI Summary 與 Comment 顯示區的頁面
5. 嘗試填入大量文字，確認內容可以垂直捲動顯示
6. 檢查中英文翻譯是否顯示正確
- 整個方框中文與英文翻譯文字應該正確對應顯示
- AI Summary 與 Comment 內容應該能完整顯示且可捲動
#1218 
目前僅修正 layout 與顯示問題，後續若有 AI 回傳格式調整會再另開 PR 處理。

[feature]-fix llm review bug 

---

Dockerfile

Adds Python dependencies to the Dockerfile to address an issue where `node-sass` fails to rebuild its binary on ARM-based macOS systems. This ensures compatibility and successful builds in such environments.
1. Clone the repository on an ARM-based macOS system.
2. Build the Docker image using `make run_dev` command.
The Docker image should build successfully on ARM-based macOS systems, and the `node-sass` binary should be rebuilt without errors.
#1206

fix: add Python dependencies in Dockerfile for ARM-based macOS

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/reviews/views.py
src/templates/default/dashboard_base.html

- [x ] **New feature**
新增「第二次審稿」區塊標題
顯示 Stage 2 的 摘要（summary）
顯示 Stage 2 的 評論（comment）
顯示 Stage 1 與 Stage 2 之間的 差異（diff）
僅當提案已有第二筆 LLMReview 記錄時才渲染此區塊，若僅有一次審稿則不顯示。
1. 進入審稿的頁面
2. 點選其中一個稿件
3.驗證「第二次審稿」區塊是否出現，並確認其中包含：
摘要：對應第二次審稿的 summary 欄位
評論：對應第二次審稿的 comment 欄位
Diff：呈現 Stage 1 與 Stage 2 之間的變更
如圖所示，並對應到後台第二次 AI 審稿的內容
#1238 
#1230

feat : show second AI review

---

src/conftest.py
src/users/api/views.py
src/users/models.py
src/users/tests/test_api.py

- [X ] **Bugfix**
queryset
sort by speak_name
test case

Reviewer api
