src/templates/registration/password_reset_email.txt
src/templates/registration/verification_email.txt
src/users/models.py
src/users/tests/test_views_signup.py
src/users/views.py

- Fix #48 
- Add email template for #49

Add email content for account auth 

---

src/templates/registration/login.html
src/templates/registration/password_reset.html
src/templates/registration/password_reset_confirm.html
src/templates/registration/password_reset_email.txt
src/templates/registration/verification_email.txt
src/users/forms.py
src/users/urls.py
src/users/views.py

Implement password reset

---

src/templates/_includes/dashboard_tablist.html
src/templates/dashboard_base.html
src/templates/proposals/_proposal_base.html
src/templates/proposals/_proposal_create.html
src/templates/proposals/_proposal_update.html
src/templates/registration/password_change_form.html
src/templates/users/user_dashboard.html
src/templates/users/user_profile_update.html
src/users/urls.py
src/users/views.py

修改密碼頁面 Take 2

---

.editorconfig
.travis.yml

Try to fix pull request errors.

Deploy fix

---

src/core/context_processors.py
src/pycontw2016/settings/base.py
src/pycontw2016/settings/production.py
src/static/js/google_analytics.js
src/templates/base.html

加入 Google Analytics 的 JS code

---

src/core/templatetags/pycontw_tools.py
src/pycontw2016/settings/base.py
src/templates/dashboard_base.html

Show alert messages in dashboard

---

src/templates/users/user_profile_update.html

Update error message styles: fix #67

---

src/proposals/management/commands/recent_proposals.py

Cry louder

---

src/static/data/staff.yml

add staff from contact book

---

requirements/base.txt
src/proposals/management/commands/recent_proposals.py
src/proposals/management/commands/slack.py
src/proposals/tests/test_management.py
src/pycontw2016/settings/base.py

現在在 `local.env` 裡加上
```
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/Txxxx/Bxxxx/xxxxx
```
在收集最近投稿時加上參數 `--slack`，就會透過 Slack incoming webhook 傳到 #program channel
```
python manage.py recent_proposals --hour 10 --days 1 --slack
```

Add Slack integration

---

src/static/css/main.scss
src/static/css/mixins/_language.scss
src/templates/base.html

好像還是應該加一下。另外現在沒用到，不過之後可以能會需要，所以也順便加了一些中文專有的 styling。

在 template 加上語言資訊

---

src/templates/contents/zh/about/pycontw.html

先放上第一版 (中文 only)，如果還有要補充，再發 PR。
(Issue #91)

About/PyCon Taiwan 中文 (初版)

---

src/templates/contents/en/speaking/cfp.html
src/templates/contents/zh/speaking/cfp.html

Postpone Call for Proposal deadlines

---

src/templates/contents/zh/events/keynotes.html

Big thanks to 昱廷 for the translation！
Close #92.

Add translation of keynote speaker profiles

---

src/templates/contents/zh/about/pycontw.html

換成 Victor 提供的 Kaohsiung.py 介紹文。

更新 Kaohsiung.py 的介紹文

---

src/proposals/tests/views/test_create.py
src/proposals/urls.py
src/templates/users/user_dashboard.html

Disable proposal creation

---

src/static/css/base/_navigation.scss
src/templates/_includes/nav/front_nav.html

For issue #113 . 
p.s. 選單在 mobile size 仍需 click (需要 js)

Navbar 的 Dropdown 在 hover 時展開

---

src/templates/contents/en/about/pycontw.html

Review first draft of english about/pycontw

---

src/templates/contents/en/about/pycontw.html

Fix #144.
需要英文 review…… 還在這內容太長，需要再補上專有名詞的翻譯。
有個待確認的翻譯，「不定期」目前是翻譯成「irregular」但我覺得蠻怪的。

Add first draft of english about/pycontw

---

src/static/css/base/_variables.scss
src/static/css/main.scss
src/static/css/pages/_sprints.scss
src/templates/_includes/nav/front_nav.html
src/templates/contents/en/events/sprints.html
src/templates/contents/zh/events/sprints.html

Add Sprint content

---

src/reviews/views.py

Fix the issue in this comment https://github.com/pycontw/pycontw2016/pull/170#issuecomment-204727653 所以只會顯示每個人最新的 review。
ps 如果是直接覆寫 database 裡的記錄就沒這問題了……對不起我蠢@@

Only select the review of latest stage made by each reviewer.

---

src/templates/reviews/review_form.html

一次開好幾個頁面，然後看到全部都是 Dashboard 就 orz 了，連想找瀏覽器歷史都很困難⋯⋯

在 review form 頁面標題列顯示 proposal title

---

src/proposals/models.py
src/reviews/apps.py
src/reviews/models.py
src/reviews/views.py
src/static/css/pages/_proposals.scss
src/templates/reviews/_includes/previous_review_table.html
src/templates/reviews/_includes/proposal_table.html
src/templates/reviews/_includes/review_table.html
src/templates/reviews/review_form.html
src/templates/reviews/talk_proposal_list.html

Review stage 2

---

src/core/data.py

Add Photography staff list

---

src/templates/index.html

Fix Sprint date error

---

src/proposals/views/talk_list.py
src/pycontw2016/urls.py
src/static/css/main.scss
src/static/css/pages/_talks.scss
src/templates/_includes/nav/front_nav.html
src/templates/proposals/talk_proposal_list.html

Simple list all accepted talk proposals

Add Events/Talks page

---

src/static/js/reviews/talk_proposal_list.js
src/templates/reviews/talk_proposal_list.html

因為之前帶 `order` 參數的實作沒考慮其他 query string，如果要把 tab index 帶進去就會很爆炸⋯⋯所以還是暴力一點好了。

記住最後的 review tab (local storage implementation)

---

src/templates/contents/zh/registration/ticket-info.html

Take care of en Version later.

Update Ticket Info zh Version.

---

src/static/css/pages/_front.scss

修正 list item 在多行時的 indent

---

src/templates/registration/login.html
src/templates/registration/signup.html

Show django message in login and signup page

---

src/static/css/pages/_venue.scss
src/templates/contents/_base/venue.html
src/templates/contents/en/venue.html
src/templates/contents/zh/venue.html

順手清理了一下 template 繼承結構。其實就只是把共用的東西移到 `_base` 而以，沒真的改什麼東西。
修改 attribution 文字的方法是在對應的 layer 設定加上 `attributions` 設定，然後讓它顯示合適的 HTML。

改用 Thunderforest tile source

---

src/sponsors/models.py
src/sponsors/views.py

Update sponsor ordering

---

src/core/views.py
src/templates/index.html

- 調整時區
- deadline 改成 `售票結束時間 5/13`

Home latest news

---

src/templates/_includes/nav/front_nav.html

簡單加個連結到 kktix 個人贊助的頁面，增加 #61 的曝光度。

Add patron registration kktix link in navbar

---

src/templates/events/talk_list.html

Fix sponsor talk list item styling

---

src/templates/contents/en/events/pyday.html
src/templates/contents/zh/events/pyday.html

@flywindy  PyDay 的 Jan 希望增加 KKTIX 售票訊息到 PyDay 的頁面。參考了您做的售票頁面發了 PR 。

增加 PyDay 售票資訊內容

---

src/static/css/pages/_keynotes.scss
src/templates/contents/en/events/keynotes.html
src/templates/contents/zh/events/keynotes.html

Add keynote talks info for Amber, Paul, and Steve

Add keynote talk info

---

src/conftest.py
src/events/admin.py
src/events/tests/test_admin.py
src/events/tests/test_management.py

有個欄位名稱不對（應該是 `begin_time` 不是 `start_time`），然後 filter 的邏輯有問題。
順便加了幾個測試。
雖然我覺得這些應該根本不會用到⋯⋯

修正一些 event admin 的問題

---

src/events/tests/conftest.py
src/events/tests/test_views.py
src/templates/events/schedule.html

Close #270. Tests added to prevent future errors. :)

Fix link on schedule page

---

src/static/js/events/schedule.js
src/templates/events/schedule.html

Schedule update hash on scroll

---

src/templates/_includes/nav/front_nav.html
src/templates/contents/en/events/overview.html
src/templates/contents/en/events/tutorials.html
src/templates/contents/zh/events/overview.html
src/templates/contents/zh/events/tutorials.html
src/templates/index.html

Originally made by @chairco in #274

Add tutorial info

---

src/templates/contents/_default/surveys/post_tutorial_mysql.html

直接嵌入 Typeform 問卷：https://ccclarc.typeform.com/to/DZgOt0

新增 Tutorial 課後問卷 static page

---

src/templates/base.html
src/templates/index.html

template: pass `active` to avoid AttributeError

---

src/templates/pycontw-2017/contents/en/registration/financial-aid.html
src/templates/pycontw-2017/contents/en/registration/ticket-info.html
src/templates/pycontw-2017/contents/en/venue.html
src/templates/pycontw-2017/contents/en/venue/accommodation.html
src/templates/pycontw-2017/contents/en/venue/travel-info.html
src/templates/pycontw-2017/contents/zh/registration/financial-aid.html
src/templates/pycontw-2017/contents/zh/registration/ticket-info.html
src/templates/pycontw-2017/contents/zh/venue.html
src/templates/pycontw-2017/contents/zh/venue/accommodation.html

Add contents (en/zh):
- venue.html
- venue/accommodation.html
- venue/travel-info.html (只有en)
- registration/financial-aid.html
- registration/ticket-info.html 
_(日期網址槓掉，價錢地點保留）_

Add contents of venue/registration

---

src/templates/pycontw-2017/contents/en/registration/financial-aid.html
src/templates/pycontw-2017/contents/en/registration/ticket-info.html
src/templates/pycontw-2017/contents/en/venue.html
src/templates/pycontw-2017/contents/en/venue/accommodation.html
src/templates/pycontw-2017/contents/en/venue/travel-info.html
src/templates/pycontw-2017/contents/zh/registration/financial-aid.html
src/templates/pycontw-2017/contents/zh/registration/ticket-info.html
src/templates/pycontw-2017/contents/zh/venue.html
src/templates/pycontw-2017/contents/zh/venue/accommodation.html

Changed pages
- ticket-info
- financial-aid
- venue
- travel-info
- accommodation
> note: travel-info only have en

#288 Update pages of contents with proper tags

---

src/templates/pycontw-2017/base.html

#327  我手腳太慢沒跟上 TP 大的 merge pycontw-2017 速度，這個頁面修正好已經正常了。

fix venue.html pages not show OpenstreetMap

---

src/static/css/pages/_dashboard.scss
src/static/css/pages/_proposals.scss
src/static/js/proposals/proposal_update.js
src/static/pycontw-2017/_includes/_bootstrap-variables.scss
src/templates/default/boilerplate.html
src/templates/default/proposals/_proposal_update.html

Simple widget to show scroll progress

---

src/static/css/pages/_proposals.scss
src/templates/default/_includes/proposal_example_modal.html

原本範例的 modal 的內容沒有列出題目、類型等可能會讓投稿者對於範例摸不著頭緒。把這些內容新增上去畫面顯示如下：

更新 example_modal.html 內容

---

src/proposals/views/update.py
src/templates/default/_includes/proposal_example_modal.html

1. Pull the example contents out with script tags instead of embedding inside JavaScript
2. Put example contents inside ProposalUpdateView and generate HTML using templates
3. Translate all the text contents into English

Add i18n to proposal example modals

---

src/templates/pycontw-2017/contents/en/speaking/cfp.html

Fix typos and add English content (#367)

---

src/templates/pycontw-2017/contents/en/registration/financial-aid.html

Minor Wording Fix

---

src/templates/pycontw-2017/contents/en/registration/financial-aid.html
src/templates/pycontw-2017/contents/zh/registration/financial-aid.html

This commit tweaks financial aid text.
The result is showed in the following images.

Tweak financial aid text

---

src/templates/pycontw-2017/contents/zh/registration/financial-aid.html

1. Fix form's url address.
2. Update 5 point in application How-Tos.

Fix form's url and update application How-Tos

---

src/reviews/models.py
src/templates/pycontw-2017/contents/en/events/talk.html
src/templates/pycontw-2017/contents/en/speaking/cfp.html
src/templates/pycontw-2017/contents/zh/events/talk.html
src/templates/pycontw-2017/contents/zh/speaking/cfp.html

+ Add acceptance talk list in /events/talk.html.
+ Update announcement of acceptance date in speaking/cfp.html.

Update PyContw2017 acceptance talk list

---

src/templates/pycontw-2017/contents/en/events/tutorial.html
src/templates/pycontw-2017/contents/zh/events/tutorial.html

Add tutorial's details

---

src/templates/pycontw-2017/contents/en/events/sprints.html
src/templates/pycontw-2017/contents/zh/events/sprints.html

Add June 12th sprint activity and detail.

Add Sprints activity on June 12th, but not have registration link yet

---

.travis.yml
README.md
tox.ini

Upgrade default settings to Python 3.6.

Set default Python to 3.6

---

requirements/dev.txt
requirements/production.txt

Reflect current packages on 2018 production.

Upgrade packages for py36

---

src/templates/pycontw-2018/_includes/menu.html
src/templates/pycontw-2018/contents/en/speaking/recording.html
src/templates/pycontw-2018/contents/zh/speaking/recording.html

Add speaking recording.html, Fix issue #412

---

src/templates/pycontw-2018/contents/en/about/community.html
src/templates/pycontw-2018/contents/en/about/pycontw.html
src/templates/pycontw-2018/contents/zh/about/community.html
src/templates/pycontw-2018/contents/zh/about/pycontw.html

Fix names and hyperlink properties

---

src/core/models.py

Model EventInfo add new choices IOT.

---

src/proposals/resources.py

It's somehow handy to do this.

Add language field to proposal export

---

src/reviews/models.py
src/templates/default/reviews/_includes/previous_review_table.html
src/templates/default/reviews/_includes/review_table.html
src/users/admin.py
src/users/models.py

- Based on changes made by @jneo8 in #422
- Changes on i18n messages are discarded
- Uses PK

Resolves #421: Show Reviewer ID

---

src/core/context_processors.py
src/templates/pycontw-2018/base.html

Remove GA track

---

package.json
src/static/pycontw-2018/scripts/venue.js
yarn.lock

地圖最新版：
https://jsfiddle.net/vgjtrzjv/136/

easyButton

---

src/templates/pycontw-2018/_includes/menu.html
src/templates/pycontw-2018/events/talk_list.html

Notes:
- 大致上翻譯都能動，但是 talks 頁面因為原本寫研討會期間 "three days" 改成了 "two days" 所以整段翻譯要重上
- 我有點雞婆的把 menu 上的「Speaking」換成「Events」了，不過應該是沒有錯吧

Add talks list page

---

src/static/pycontw-2018/styles/_tag.scss
src/static/pycontw-2018/styles/page.scss
src/static/pycontw-2018/styles/pages/_talks.scss
src/static/pycontw-2018/styles/site.scss
src/templates/pycontw-2018/events/talk_list.html
src/users/models.py

Talks anchor

---

src/events/api_proposals.py
src/events/urls.py

Add a new http API for CCIP events data

Add a new http API for CCIP APP events data.

---

src/templates/pycontw-2018/_includes/menu.html
src/templates/pycontw-2018/contents/en/events/sprints.html
src/templates/pycontw-2018/contents/zh/events/sprints.html

是說我總覺得哪裡怪怪的，但是就先放好了，之後 Meetup 上面活動開好之後再多加報名連結，會用跟 Tutorial 頁面一樣的報名按鈕。

增加 Sprint 頁面的內容

---

src/static/pycontw-2018/styles/pages/_schedule.scss
src/templates/pycontw-2018/events/schedule_create.html

修掉小山丘的角角和 td

---

src/static/pycontw-2019/_includes/base/_variables.scss
src/static/pycontw-2019/styles/_box.scss
src/static/pycontw-2019/styles/_menu-mobile.scss
src/static/pycontw-2019/styles/_nav.scss
src/static/pycontw-2019/styles/index.scss
src/static/pycontw-2019/styles/page.scss
src/templates/pycontw-2018/_includes/error-styles.html
src/templates/pycontw-2019/_includes/error-styles.html
src/templates/pycontw-2019/_includes/hero.html
src/templates/pycontw-2019/contents/_base.html

統一sponser頁面主色調和2019主頁面相同
修改日期錯誤

Sponser page theme color

---

src/core/context_processors.py

Update the volunteer form links (ref issue #485)

---

src/templates/pycontw-2019/contents/en/sponsor/sponsor.html
src/templates/pycontw-2019/contents/zh/sponsor/sponsor.html

modify zh version of why sponsor pages

---

src/templates/pycontw-2019/contents/_pycontw.html
src/templates/pycontw-2019/contents/zh/sponsor/sponsor.html

修改在這個議題所提到的問題，增加了 footer 的 2018 連結。

revise issue of 「 在「研討會歷史」頁面的 footer 增加 2018 的網站連結 」

---

src/core/context_processors.py

Correct the link of "Become a volunteer" to link to the google-forms of right language version.

Correct the link of "Become a volunteer"

---

src/core/context_processors.py
src/pycontw2016/settings/base.py
src/pycontw2016/settings/production/base.py
src/templates/default/boilerplate.html
src/templates/pycontw-2019/base.html

Remove GA codes

---

src/reviews/views.py

@adrianliaw How do you think about this?

Fill prev round review in form initial

---

src/static/pycontw-2019/styles/page.scss
src/templates/pycontw-2019/contents/zh/sponsor/sponsor.html

Solve issue #520 
Right-align the closing paragraph in sponsor page.

Solve Issue #520 

---

src/templates/pycontw-2019/_includes/menu.html

Solve issue #534

---

requirements/base.txt

This pull request addresses https://github.com/pycontw/pycon.tw/pull/532#discussion_r279249422

Add a short description on libsass for pycontw-2017

---

requirements/base.txt
requirements/production.txt

Move version pinning of django-picklefield to requirements/base.txt

---

src/events/views.py

Bug fix, cancel talks page queryset cache

Buf fix, cancel talks queryset cache

---

src/static/pycontw-2019/styles/_palette.scss
src/static/pycontw-2019/styles/pages/_talks.scss
src/templates/pycontw-2019/events/talk_detail.html

modified:   src/static/pycontw-2019/styles/_palette.scss
modified:   src/static/pycontw-2019/styles/pages/_talks.scss
modified:   src/templates/pycontw-2019/events/talk_detail.html
fixes #556
change background color with new design

Fix Issue #556

---

src/static/pycontw-2019/styles/pages/_talks.scss

Fix broken nested ol

---

src/static/pycontw-2019/styles/_palette.scss
src/static/pycontw-2019/styles/_tabbing.scss
src/static/pycontw-2019/styles/pages/_keynotes.scss
src/templates/pycontw-2019/_includes/menu.html
src/templates/pycontw-2019/contents/en/events/keynotes.html
src/templates/pycontw-2019/contents/zh/events/keynotes.html

Feat keynote

---

src/core/context_processors.py
src/events/templatetags/events.py
src/events/views.py
src/pycontw2016/settings/base.py
src/pycontw2016/settings/production/pycontw2019.py
src/static/pycontw-2019/assets/icon-room-R3.svg
src/static/pycontw-2019/styles/_palette.scss
src/static/pycontw-2019/styles/pages/_schedule.scss
src/templates/pycontw-2019/_includes/menu.html
src/templates/pycontw-2019/events/schedule_create.html

Schedule ux

---

src/static/pycontw-2019/styles/_palette.scss
src/static/pycontw-2019/styles/pages/_portal.scss
src/templates/pycontw-2019/_includes/menu.html

Update 2019 portal style

---

src/templates/pycontw-2019/_includes/staff.html

complete staff html
將上次未填寫的剩下人員名單補齊

feat: 🎸 complete staff html

---

Dockerfile
docker-compose.yml
src/core/tests/test_views.py
src/events/tests/test_admin.py
src/pycontw2016/settings/production/pycontw2020.py
src/pycontw2016/settings/testing/pycontw2020.py
src/pytest.ini

Adjust the paths and names for docker related files.

Adjust environment for 2020

---

src/static/pycontw-2020/styles/_pycontw-year-ribbon.scss
src/static/pycontw-2020/styles/index.scss
src/templates/pycontw-2020/_includes/pycontw_year_ribbon.html
src/templates/pycontw-2020/index.html

Add year ribbon and fix volunteer block margin

---

src/static/pycontw-2020/scripts/venue.js
src/static/pycontw-2020/styles/pages/_venue.scss
src/templates/pycontw-2020/contents/_base.html
src/templates/pycontw-2020/contents/_venue.html
src/templates/pycontw-2020/contents/en/venue.html
src/templates/pycontw-2020/contents/zh/venue.html

Add the following content
* From TPE to NCKU
* From KHH to NCKU
* From NCKU to Goodideas-Studio

feat: add 2020 venue

---

yarn.lock

Security updates for node packages.

Upgrade node packages (yarn.lock updated)

---

src/templates/pycontw-2020/contents/en/about/code-of-conduct.html
src/templates/pycontw-2020/contents/en/event/open-spaces.html
src/templates/pycontw-2020/contents/en/speaking/cfp.html
src/templates/pycontw-2020/contents/en/speaking/recording.html
src/templates/pycontw-2020/contents/en/speaking/talk.html
src/templates/pycontw-2020/contents/en/speaking/tutorial.html

- Fix some typos like "feedbacks" and grammar issues raised by Grammarly.

improvement: Fix some typos and grammar issues

---

src/templates/pycontw-2020/contents/en/sponsor/prospectus.html
src/templates/pycontw-2020/contents/en/sponsor/sponsor.html
src/templates/pycontw-2020/contents/zh/sponsor/prospectus.html
src/templates/pycontw-2020/contents/zh/sponsor/sponsor.html

Placeholder for prospectus

---

.vscode/settings.json
src/templates/pycontw-2020/contents/en/speaking/cfp.html
src/templates/pycontw-2020/contents/zh/speaking/cfp.html

Fix #666
- Replace some () to （）
- Replace AoE descriptions

improvement: fix for writing-guidelines #666

---

src/templates/pycontw-2020/contents/zh/sponsor/prospectus.html

The very beginning sponsorship prospectus contents.

sponsor: prospectus: init packages

---

src/static/css/base/_navigation.scss
src/static/css/components/_buttons.scss
src/static/css/pages/_dashboard.scss
src/static/css/pages/_proposals.scss
src/static/css/pages/_registration.scss
src/templates/default/_includes/nav/nav_base.html
src/templates/default/boilerplate.html

update logo and dashboard color scheme
solve issue #661

Dashboard 2020 Styling #661

---

src/static/css/pages/_registration.scss

update button's color

---

src/static/pycontw-2020/styles/_index-hero.scss
src/static/pycontw-2020/styles/_layout.scss
src/static/pycontw-2020/styles/_menu-desktop.scss
src/static/pycontw-2020/styles/_menu-mobile.scss
src/static/pycontw-2020/styles/_nav.scss

Fixes several style bug:
1. Footer link hover color
2. Navbar provintia icon spacing
3. My PyCon (desktop menu) offset
4. 1 pixel white from index hero banner
First two are feedback from the designer.
Reference: https://docs.google.com/document/d/1YidtzUeSw_OwmgtGveIkn-fUgNxMtd5KqtxUrD4ce7Y/edit

2020 style

---

src/templates/pycontw-2020/contents/en/sponsor/prospectus.html

Add more English translation. The progress is around 40% now.

sponsor: prospectus: more en translation

---

src/static/css/pages/_dashboard.scss
src/static/css/pages/_proposals.scss
src/templates/default/dashboard_base.html
src/templates/default/reviews/_includes/proposal_table.html
src/templates/default/reviews/_includes/review_table.html
src/templates/default/users/_includes/dashboard_proposal_table.html

Also tried to fix #672, but I think the problem in 672 is much bigger than this one, since it has more tables and more columns in it. However, this fix some of them.

Fixes #675. Proposal name too long causes problem in mobile

---

src/static/pycontw-2020/styles/pages/_sponsorship-prospectus.scss
src/templates/pycontw-2020/contents/en/sponsor/prospectus.html

1. Integrate Cynthia 's translation (with little wording tweak)
2. Fixed the table look of the English page

Complete 1st version of English page

---

src/templates/pycontw-2020/contents/zh/sponsor/prospectus.html

Follow-up quick fix of https://github.com/pycontw/pycon.tw/pull/705/files

sponrsor: prospectus: fix typo of package id

---

src/core/templatetags/pycontw_tools.py
src/static/pycontw-2020/styles/_menu-desktop.scss
src/templates/pycontw-2020/_includes/menu.html

As mentioned in #654, displaying the item in the navigation menu that indicates the current location as being barred is desired.

Bar the item in navigation menu if it's current location

---

src/templates/pycontw-2020/contents/zh/sponsor/sponsor.html

sponsor: sponsor: fix wording

---

src/proposals/admin.py

Remote field is not added in admin. Add it to admin to navigate the value.

Add remote field in admin

---

src/core/context_processors.py

update volunteer google form url

---

src/locale/zh_Hant/LC_MESSAGES/django.po
src/templates/pycontw-2016/contents/zh/speaking/cfp.html
src/templates/pycontw-2017/contents/zh/speaking/cfp.html
src/templates/pycontw-2018/contents/zh/speaking/cfp.html
src/templates/pycontw-2019/contents/zh/speaking/cfp.html
src/templates/pycontw-2020/contents/zh/speaking/cfp.html

建立 is more like a zh_tw / 正體中文 wording instead of 創建 : )

translation: fix zh wording

---

README.md

Behaviour change in docker-library/postgres newest version.
See [docker-library/postgres issue(#681)](https://github.com/docker-library/postgres/issues/681)

Update db setup of README.md

---

README.md

Update postgres connection and superuser creation in README.md.

Update db connection and su creation in README.md

---

src/proposals/management/commands/export_proposals_create_time.py

**Add command:**
`python manage.py export_proposals_create_time`
**Output example:**
`
[
{
"proposal_type(id)": "talk(1)",
"title": "測試01",
"speaker_name": "speaker_name",
"email": "speaker@gmail.com",
"created_at": "2020-05-06 22:00:00"
}
]
`

export_proposals_create_time

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

So we will have better discipline when working together as a team : )

Update issue and create pull request templates

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Following PR https://github.com/pycontw/pycon.tw/pull/770 and add the unexpectedly missing file.

Fixup: missing pull request template creation file

---

README.md

I finally have a moment to try what @alice6373  has contributed with https://github.com/pycontw/pycon.tw/pull/736 and https://github.com/pycontw/pycon.tw/pull/758 . This pull request intends to make the description more comprehensive.

README: update db and .env description

---

src/reviews/context.py
src/static/css/pages/_proposals.scss
src/templates/default/_includes/dashboard_tablist.html
src/templates/default/reviews/_includes/proposal_table.html

---
name: Pull request
about: Proposa a pull request
title: "Issue762 update proposal order"
labels: 
assignees: ''
---
1. 修改tab分頁鏈接, 預設引導審查數DESC排序。
2. 透過dj-registry設置字段reviews.enough, 調整足夠的審查數。

update proposal order

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Update template for GitHub issue and pull request. In the original version, the style of 2 issue templates are different.
* Create a pull request after this PR is merged
* Create an issue after this PR is merged
* Create pull requests/issue with new template

unify and update github template style

---

src/templates/pycontw-2020/contents/en/registration/financial-aid.html
src/templates/pycontw-2020/contents/zh/registration/financial-aid.html

Change PyCon Taiwan 2020 FA Deadline from 6/21 to 7/15

improvement: update FA deadline

---

src/core/tests/test_views.py

* Avoid using test client to access external site after redirecting from
schedule page
- Adding assertRedirections in test_content_pages_links to avoid test client access external websites after redirecting from /events/schedule/
- Adding testing to check if the redirection on /events/schedule/ page works correctly
1. Running `pytest -n 2 --cov=.` directly to check all functions work as usual
2. Adding external url to SCHEDULE_REDIRECT_URL in `base.py` and run `pytest -n 2 --cov=.` to check the test works normally
A clear and concise description of what you expected to …

Fix testing in test_content_pages_links

---

src/core/context_processors.py
src/templates/pycontw-2020/_includes/menu.html
src/templates/pycontw-2020/contents/en/registration/ticket-info.html
src/templates/pycontw-2020/contents/zh/registration/ticket-info.html

add 2020 ticket-info.html (en/zh)

en/zh ticket-info.html

---

src/static/pycontw-2020/styles/pages/_ticket-info.scss
src/templates/pycontw-2020/contents/en/registration/ticket-info.html
src/templates/pycontw-2020/contents/zh/registration/ticket-info.html

依據新的設計稿更新售票頁面的 html 以及 CSS 檔案
1. Go to ticket info page `localhost:8000/<lang>/registration/ticket-info/` with web browser.

update ticket info page style

---

src/static/pycontw-2020/styles/_button.scss
src/static/pycontw-2020/styles/_index-partners.scss
src/static/pycontw-2020/styles/_popup.scss
src/templates/pycontw-2020/_includes/sponsors.html
src/templates/pycontw-2020/index.html

* include _inlcudes/sponsors.html in index.html
* Add new sponsors.html
* Update popup card border, close icon style, link-to-website btn style
* Add grid style to sponsors logos
* Add new sponsors.html with grid layout style
* Update popup card border, close icon style, link-to-website btn style
1. Running command `python3 manange.py runserver`
2. Open your preferred browser and go to `localhost:8000`
3. …

[Feat] Add sponsors' logo in index page

---

src/templates/pycontw-2020/contents/en/events/pyhug.html
src/templates/pycontw-2020/contents/en/events/taipei-dot-py.html
src/templates/pycontw-2020/contents/en/events/warmup-session.html
src/templates/pycontw-2020/contents/zh/events/pyhug.html
src/templates/pycontw-2020/contents/zh/events/taipei-dot-py.html
src/templates/pycontw-2020/contents/zh/events/warmup-session.html

Add more existing warm-up session events
Go to the warm-up session page and its sub-pages to check the contents.
The event and its info has been added in both zh and en version.
**expected screenshots**
We may ask for the speaking to create pull requests to add their own self-introduction. Besides, I really like to use the website as a event archive/museum!

Add new warm-up events

---

src/static/pycontw-2020/styles/_index-partners.scss

* Update max-height: 125px to height: 125px
1. Running command python3 manange.py runserver
2. Open your preferred browser and go to localhost:8000
3. Scroll down in this page
The SVG image could show normally
#835 
If applicable, add screenshots to help explain your …

style(sponsors): Fix not showing svg image

---

src/static/pycontw-2020/styles/_index-partners.scss

Revert "style(sponsors): Fix not showing svg image"

---

src/templates/pycontw-2020/contents/en/events/sprints.html
src/templates/pycontw-2020/contents/zh/events/sprints.html

Update sprint page's content
1. Go to the URL '/events/sprints/'
Content align with https://docs.google.com/document/d/1A-fNFpjPSDh1f2Ea_Uoo070YAn9narw9ImP0KEgtvlY/edit
#842 

feat(sprints): update to 2020 content

---

src/static/pycontw-2020/assets/keynotes/peter-wang.json

Add social information to Peter Wang

feat(pycontw-2020/assets/keynotes): add pater wang social

---

src/static/pycontw-2020/assets/keynotes/wenyu-su.json

Add 2020 keynote WenYu Su's session.

feat(2020-keynote): add session

---

src/static/pycontw-2020/styles/page.scss
src/static/pycontw-2020/styles/pages/_venue.scss

- Fix oversized width of map in mobile
- Also update the format of code by using SCSS formatter
1. Go to venue page in responsive mode
2. check the result
The view should looks as following screenshots
#873 
If applicable, add screenshots to help explain your …

fix(venue-page): Fix the width of map

---

.github/pull_request_template.md

The first sentence is often ignored by users when creating pull request. It may looks better and easier to be noticed if it is right after a heading.
1. create a new pull request if this pr is merged into master
The github pull request template updates. The line "thanks..." order is moved down.

make the template description more explicit

---

src/templates/pycontw-2020/_includes/staff.html

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
to [how to wirte the perfect pull …

Update Staff to include Registration Team

---

src/templates/pycontw-2020/contents/en/events/tainan-dot-py-mosut.html
src/templates/pycontw-2020/contents/en/events/warmup-session.html
src/templates/pycontw-2020/contents/zh/events/tainan-dot-py-mosut.html
src/templates/pycontw-2020/contents/zh/events/warmup-session.html

add warm up session tainan.py x mosut page
Go to Event -> Warm-up Session page
An entry to tainan.py x mosut with working link
Resolves #890

feat(event): add warm up session tainan.py x mosut page

---

src/templates/pycontw-2020/events/talk_detail.html

Display location and time in event detail page
1. Open anyone event detail page.

Display location and time in event detail page

---

src/static/pycontw-2020/styles/pages/_community-track.scss

I made the  font in community-track page larger.
1. Go to localhost:8000/conference/community-track
2. The font in the overview and each topic is too small
It should be easier to read.
Before:
After:

Make the font larger

---

src/templates/pycontw-2020/base.html
src/templates/pycontw-2020/contents/_default/events/job-listings.html

Apply meta data for SEO according to Stacy's suggestion.
1. Check the job-listings page looks well.
Google ranking of this page is better.

Apply seo info for job-listings

---

src/templates/pycontw-2020/contents/en/venue.html
src/templates/pycontw-2020/contents/zh/venue.html

- Add leave information section to venue page.
1. Go to Venue Page
2. Scroll down to "社群議程後交通指南"(or Transportation for Leaving PyCon after Social Community Track)
#920
to [how to wirte the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull- …

feat(venue): Add leave information

---

src/static/pycontw-2020/assets/keynotes/mariatta-wijaya.json
src/static/pycontw-2020/assets/keynotes/peter-wang.json
src/static/pycontw-2020/assets/keynotes/wenyu-su.json

Add slido link to keynote infomation
1. Go to keynote page
2. Click on Slido tab
You will see your view like following screenshot 

feat(keynote): Add slido link to keynote info

---

src/templates/pycontw-2020/events/community_track.html

Update the shuttle bus departure time for the community track.
1. Go to localhost:8000/conference/community-track
The correct departure time.

update shuttle bus info

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/pycontw-2020/styles/index.scss
src/templates/pycontw-2020/_includes/menu.html
src/templates/pycontw-2020/_includes/portal.html

add open space link in index portal
1. Go to ``localhost:8000``

add open space link in portal

---

src/static/pycontw-2020/styles/_layout.scss

- Fix margin of the main section in mobile view
1. Go to https://tw.pycon.org/2020/zh-hant/conference/talk/1164337168361980290/
2. Open the debugger and switch to the mobile mode or view the page from your phone.
3. Check if the layout is displayed normally.
#943 …

fix(talk_detail): Fix margin of main section in mobile view

---

src/templates/pycontw-2020/contents/_default/conference/keynotes.html

update Slides display url link

---

src/core/templatetags/pycontw_tools.py
src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/css/pages/_proposals.scss
src/templates/default/proposals/_proposal_update.html
src/users/models.py

1. change the description to 1000 characters the description
2. Hide tutorial in modification step
3. Word wrap for proposal & review comment

Fix bugs proposal system testing

---

src/static/css/pages/_proposals.scss

fix review content wordwrap

---

requirements/base.txt

Fix test error when you run test in local dev environment

fix(unittest): fix test error in local env

---

docker-compose.yml
src/pycontw2016/settings/production/pycontw2021.py

We'd liked to change the endpoints of frontend & backend:
- frontend: `tw.pycon.org/` -> `tw.pycon.org/2021`
- backend: `tw.pycon.org/2021` -> `tw.pycon.org/prs`
Related PRs:
- [pycontw-2021/#23](https://github.com/pycontw/pycontw-2021/pull/23)
- [pycontw-nginx#5](https://github.com/pycontw/pycontw-nginx/pull/5)

hotfix(route): change backend route & frontend endpoint

---

src/users/urls.py
src/users/views.py

Replace url() to path(), remove unused import and legacy code.
1. Go to 'http://localhost:8000/en-us/accounts/password-reset/'.
2. Input the email you want to reset password.
3. Go to inbox open the reset password email.
Should see the reset password url is complete.
(look like this: http://localhost:8000/en-us/accounts/%5Epassword-reset/Mg/al66fj-8162ce391503f44a92ca5a425ef48bcc/)

fix(users): Fix reset password

---

src/events/api/urls.py
src/events/api/views.py

Response format
```JSON
{
"data": [
{
"date": "2021-10-02",
"name": "第 1 天",
"rooms": [
"1-r3",
"2-all",
"3-r012",
"4-r0",
"5-r1",
"6-r2"
],
"slots": {
"2-all": [
{
"event_id": 146,
"event_type": "custom",
"title": "Registration & Breakfast",
"speakers": [],
"begin_time": "2021-10-02 00:30:00",
"end_time": "2021-10-02 00:50:00",
"is_remote": false,
"recording_policy": true,
"language": "",
"python_level": "",
"break_event": false
},
...
],
...
},
"timeline": {
"begin": "2021-10-02 00:30:00",
"end": "2021-10-02 12:00:00"
}
},
...
]
}
```
1. API endpoint: http://localhost:8000/api/events/schedule/ …

Schedule api

---

src/attendee/api/views.py

The room names returned from live API in `attendee` app are hard-coded as `R1`, `R2`, `R3`, etc, which is not complied to the naming convention used in PyCon TW 2021 (starts from `R0`). This PR adopts the substring in the registry key (with its prefix removed) as the room name. e.g. The key of an entry in registry is `pycontw-<year>.live.R3`, the room name of this entry would be `R3`.

fix(ext/live): parse room name from registry key

---

src/events/api/serializers.py

- [ x ] **New feature**
Add lang and level field to TalkList, TutorialList and SponsoredList API.
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
to [how to wirte the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pul …

Feat: Add lang and level field for talkApi

---

src/ccip/views.py

fix(ccip/views.py): Replace data source from file to db

---

src/events/api/views.py

Fix timezone in schedule API
1. Go to /api/events/schedule

fix(events/api/views.py): Fix timezone

---

src/locale/zh_Hant/LC_MESSAGES/django.po

Fix login error when use zh-hant.
1. Go to 'http://localhost:8000/prs/zh-hant/accounts/login/'
Can see login page correctly

fix(django.po): Fix KeyError

---

src/proposals/forms/proposals.py
src/proposals/tests/forms/test_proposal.py

This field is essential to make the update form submittable.
https://discord.com/channels/752904426057892052/753841328198254642/955417991409975306
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
to [how to wirte the perfect pull …

Add pre_recorded_policy to proposal update form

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/static/css/base/_navigation.scss
src/static/css/components/_buttons.scss
src/static/css/pages/_dashboard.scss
src/static/css/pages/_registration.scss
src/static/css/vendors/bootstrap/_navbar.scss
src/static/pycontw-2022/_includes/base/_variables.scss
src/templates/default/_includes/nav/nav_base.html

- Fix landing page based on design spec.
1. Go to `/accounts/login`
與 Designer 討論過後，目前樣式更改為(Update at 2022/Apr/22 ):
#1059

feat: fix landing page based on design spec

---

src/proposals/admin.py
src/proposals/resources.py

modified:   src/proposals/admin.py
modified:   src/proposals/resources.py
close #778 
1. Go to tutorialproposal at admin site 
2. Click on export
3. check the content of csv
在後台(admin site)新增export 出各種格式檔案
#778 
If applicable, add screenshots to help explain your …

Export tutorial proposal

---

src/sponsors/admin.py

feat(sponsor|admin): show order value

---

src/ccip/views.py

fix ccip api server error with empty room and start end time
#1095

fix: fix ccip api with empty room start and end time

---

src/events/api/views.py

fix(events): provide time in UTC and ISO format in API response

---

enter_dev_env.sh

* setting default platform to linux/arm64 when using arm64 machine.
1. Follow instuctions in `deploy_docker_dev.md`
Containers built successfully.
#1079
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

Add configuration in enter_dev_env script for M1 machine

---

src/locale/en_US/LC_MESSAGES/django.po
src/locale/zh_Hant/LC_MESSAGES/django.po
src/templates/default/reviews/_includes/review_stage_2_desc.html
src/templates/default/reviews/talk_proposal_list.html

- Improve some English grammar for better readability
- Replace the term `speaker` in the description with the `submitter` to avoid misunderstanding

improve the English description of review stage 2 to make it clearer

---

.github/workflows/ci.yaml
requirements/ci.txt

move code cov to github actions

feat: add code cov on github actions

---

.github/workflows/ci.yaml
requirements/ci.txt

The CI requirements file is almost the same as the dev requirements file. Let CI also install from the latter and the former one can be deleted safely.

chore: rm CI requirements

---

src/templates/pycontw-2025/contents/en/about/code-of-conduct.html
src/templates/pycontw-2025/contents/zh/about/code-of-conduct.html

fix: the position of a tag

---

src/reviews/views.py

- [x ] **New feature**
- Overall summary
- Comment section
- Category grouping
1. Run the project locally
2. Navigate to the  review page
3. You should see the new layout with mock AI review data displayed
The AI review section should show categorized comments, a summary, and be visually aligned with existing styles.

 resolve CI lint errors including import order and whitespace

---

src/proposals/api/serializers.py
src/proposals/api/urls.py
src/proposals/api/views.py
src/proposals/tests/api/test_llm_review_api.py

- [ x] **New feature**
Implement LLM review API endpoints and serializer

feat(llm-review): implement LLM review API endpoints and serializer

---

src/templates/default/dashboard_base.html

fix:hide the window

---

src/static/css/pages/_registration.scss
src/users/forms.py

This PR resolves the alignment and text truncation issue for the submit button on the registration form. Additionally, it improves the responsive layout of the login page to slightly enhance the mobile user experience.
1. Clone the repo and start the dev server.
2. Navigate to the Account Creation page.
3. Verify that the submit button is properly aligned and the text is fully visible.
4. Navigate to the login page on a mobile device or resize the browser window to a smaller width.
#1236

fix: improve button layout and responsiveness in registration forms

---

src/templates/default/dashboard_base.html

fix: add the sperate

---

src/users/views.py

- [ X] **Bugfix**
首頁要用的api不需要login

fix:remove the decorator for login

---

src/pycontw2016/settings/base.py

- [X ] **Bugfix**
change to this year

fix:change to this year

---

src/pycontw2016/settings/base.py

- [x ] **Bugfix**
the coc version

fix: the coc vserion
